"""All eleven milestones in the hour model sessions, in actions and minutes.

Counts agree with the milestone ladder. For every reached milestone, the
replay and keypress timeline supply its first time and action count. A zero
count has no median; a reached milestone without a timestamp fails instead
of silently disappearing from the table. Prints tables/milestones.tex;
preflight.py writes it.
"""
import json
import os
import statistics as st
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import field  # noqa: E402

ROWS = (("reached the world map", "crossing", "map"),
        ("picked up an item", "obtained", "item"),
        ("entered a location", "scene", "location"),
        ("spoke with the hermit", "hermit", "hermit"),
        ("held the compass", "compass", "compass"),
        ("recruited a party member", "recruited", "party"),
        ("entered a battle", "battle", "battle"),
        ("ended a battle", "ended", "ended"),
        ("gained experience", "exp", "exp"),
        ("reached level 2", "level", "lv 2"),
        ("held a book", "book", "book"))


def hour_rows():
    return [r for r in field.played(field.load_runs(dedup=False))
            if not field.is_random(r["agent"])]


def first_second(e, name):
    if name == "crossing":
        return e.get("first_black_second")
    if name == "recruited":
        return None if e.get("recruited_minute") is None else e["recruited_minute"] * 60 / e["speed"]
    if name == "scene":
        m = (e.get("scenes") or {}).get("first_minute")
        return None if m is None else m * 60 / e["speed"]
    if name == "ended":         # won or lost, whichever came first
        ms = [m for n in ("defeat", "won") for m in (e.get(n) or {}).get("minutes", [])[:1]]
        return min(ms) * 60 / e["speed"] if ms else None
    p = e.get(name) or {}
    return None if not p.get("minutes") else p["minutes"][0] * 60 / e["speed"]


def actions_by(marks, second):
    return sum(1 for m in marks if m["t"] <= second)


def summarize(rows=None):
    if tuple(key for _, _, key in ROWS) != tuple(field.SHORT):
        raise ValueError("the milestone table must cover the ladder in the same order")
    rows = hour_rows() if rows is None else rows
    out, timelines = [], {}
    for index, (label, name, _) in enumerate(ROWS):
        acts, mins = [], []
        for r in rows:
            reached = field.rungs_of(r)[index]
            if reached is None:
                raise ValueError(f"{r['id']}: no reading for {label!r}")
            if not reached:
                continue
            e = r.get("replay")
            tl_path = os.path.join(HERE, "timelines", r["id"] + ".json")
            if not e or not os.path.exists(tl_path):
                raise ValueError(f"{r['id']}: reached {label!r} without a replay or timeline")
            if r["id"] not in timelines:
                with open(tl_path, encoding="utf-8") as f:
                    timelines[r["id"]] = json.load(f)
            tl = timelines[r["id"]]
            sec = first_second(dict(e, speed=tl["speed"]), name)
            if sec is None:
                raise ValueError(f"{r['id']}: reached {label!r} without a replay timestamp")
            acts.append(actions_by(tl["marks"], sec))
            mins.append(sec * tl["speed"] / 60)
        out.append((label, len(acts), st.median(acts) if acts else None,
                    st.median(mins) if mins else None))
    return out


def main():
    out = summarize()
    print("% generated by figures/emit_milestones.py from the replays and timelines; do not hand-edit")
    print("\\begin{tabular}{@{}lrrr@{}}")
    print("\\toprule")
    print("Milestone & Sessions & Median actions & Median minute \\\\")
    print("\\midrule")
    for label, n, a, m in out:
        action = "--" if a is None else "%.0f" % a
        minute = "--" if m is None else "%.0f" % m
        print(f"{label} & {n} & {action} & {minute} \\\\")
    print("\\bottomrule")
    print("\\end{tabular}")


if __name__ == "__main__":
    main()
