"""The four-hour sessions that count, one row per session: the minute of the
last key, the actions sent, the minute at which each milestone was first
reached, and the milestones credited. The session id of each row is a comment
above it. Prints tables/long.tex; preflight.py writes it.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import field
import long_cohort

# (heading, reading, milestone label); experience, the second level and the
# book have no column, since no four-hour session reached them. The columns
# follow the order of the ladder, the milestone most models reach first.
MILESTONES = (("Map", "crossing", "reached\nworld map"), ("Item", "obtained", "picked up\nan item"),
              ("Location", "scene", "entered\na location"), ("Hermit", "hermit", "spoke with\nthe hermit"),
              ("Compass", "compass", "held the\ncompass"), ("Party", "recruited", "recruited a\nparty member"),
              ("Battle", "battle", "entered\na battle"), ("Ended", "ended", "ended\na battle"),
              ("Talk", "talk", "had a\nconversation"), ("Save", "save", "saved\nthe game"),
              ("Load", "load", "loaded\na save"))
_rank = {k: i for i, k in enumerate(field.hour_order())}
COLUMNS = tuple((h, n) for h, n, d in sorted(MILESTONES, key=lambda c: _rank[field.DEFINITION.index(c[2])]))


def minute_text(minute):
    if minute is None:
        return "--"
    if minute < 1:
        return "$<1$"
    return "%.1f" % minute


def first_minute(events, name):
    if name == "recruited":
        return events.get("recruited_minute")
    if name == "scene":
        return (events.get("scenes") or {}).get("first_minute")
    if name == "talk":
        return (events.get("dialogue") or {}).get("first_minute")
    if name in ("save", "load"):
        xs = events.get(name + "s") or []
        return xs[0]["minute"] if xs else None
    if name == "ended":         # won or lost, whichever came first
        ms = [(events.get(n) or {}).get("minutes") or [] for n in ("defeat", "won")]
        return min((m[0] for m in ms if m), default=None)
    minutes = (events.get(name) or {}).get("minutes")
    return minutes[0] if minutes else None


def print_row(row, label):
    events = row.get("replay")
    if not events:
        sys.exit("no replay reading for " + row["id"])
    cells = []
    for _, name in COLUMNS:
        minute = (row["exit_secs"] / 60 if row.get("exit_secs") is not None else None) if name == "crossing" else first_minute(events, name)
        cells.append(minute_text(minute))
    print("% counted-session: " + row["id"])
    print("%s & %s & %d & %s & %d \\\\" % (
        label, minute_text(long_cohort.last_key_seconds(row) / 60),
        row["actions"], " & ".join(cells), field.rungs_reached(row)))


def main():
    rows = field.load_long()
    if not rows:
        sys.exit("no four-hour session counts")
    best = {m["agent"]: m["reached"] for m in field.model_rows(rows)}
    rows.sort(key=lambda r: (-best[r["agent"]], r["agent"], r.get("started") or 0))
    print("% generated by figures/emit_long.py; session IDs are audit comments only")
    print("\\begin{tabular}{@{}l" + "r" * (3 + len(COLUMNS)) + "@{}}")
    print("\\toprule")
    print("Model & Last key & Actions & " + " & ".join(c for c, _ in COLUMNS) + " & Milestones \\\\")
    print("\\midrule")
    previous = None
    for r in rows:
        label = "\\texttt{%s}" % r["agent"] if r["agent"] != previous else ""
        previous = r["agent"]
        print_row(r, label)
    print("\\bottomrule")
    print("\\end{tabular}")


if __name__ == "__main__":
    main()
